SELECT DISTINCT CS_PAIS.COD_PAIS, CS_PAIS.NOMBRE
FROM CS_PELICULA, CS_PAIS, CS_ACTUA, CS_ACTOR, CS_CLASIFICACION, CS_GENERO
WHERE CS_PELICULA.COD_PELI = CS_ACTUA.COD_PELI
  AND CS_ACTUA.COD_ACT = CS_ACTOR.COD_ACT
  AND CS_ACTOR.COD_PAIS = CS_PAIS.COD_PAIS
  AND CS_PELICULA.COD_PELI = CS_CLASIFICACION.COD_PELI
  AND CS_CLASIFICACION.COD_GEN = CS_GENERO.COD_GEN
  AND CS_GENERO.NOMBRE = 'Comedia'
ORDER BY CS_PAIS.NOMBRE;
