SELECT COUNT(DISTINCT CS_PELICULA.COD_PELI) CUANTAS_PELIS
FROM CS_PELICULA, CS_CLASIFICACION
WHERE CS_PELICULA.COD_PELI = CS_CLASIFICACION.COD_PELI
AND (
    COD_GEN = 'BB5'
    OR COD_GEN = 'GG4'
    OR COD_GEN = 'JH6'
);
